### ISSUE TITLE
Collisions prone via concurrency

### ISSUE THREAD

**Issue by darky** [Robert4S/gleam_ref#2]
```gleam
set(myref, get(myref) + 1)
```

☝️ this design isn't luck for real production with huge amount of concurrency tasks, which deals with same ref at same time
Big probability to receive wrong ref mutation
Much better to refactor solution to something like this

```gleam
set(myref, fn(val) {val + 1})
```

And call update function inside actor itself. It's allow to avoid concurrency races and provide correct mutation of ref via pessimistic lock inside actor.

**Comment by Robert4S** [comment]
I unfortunately realised that after publishing, but that is why i quickly added the set_fun function. I still have to refactor the actor handler to actually use the functions directly though.

**Comment by Robert4S** [comment]
Updated the actor to use the function, think it should be safer now.

**Comment by Robert4S** [comment]
Side note, do you know if the vm would clean up and kill the cell actor if the garbage collector had cleaned up the process handle

**Comment by darky** [comment]
I don't think, that GC can affect Actor somehow until it stopped

**Comment by Robert4S** [comment]
so cells created will just keep a whole bunch of memory until its parent is stopped? Is there any way to hook into the GC to make custom destruction sequences for the RefCell type?

**Comment by darky** [comment]
I don't deep dived in Erlang/OTP, try to ask question in official Gleam Discord
In my opinion, you shouldn't touch memory at all, Erlang BEAM should do it best for you

**Comment by Robert4S** [comment]
meh i'll just leave it in that case. I have a feeling that Louis will not be happy if I go to the discord and he sees I made a refcell library for gleam.

**Comment by darky** [comment]
Yeah, agree. Louis already hated some of my libraries, because it's not Gleam idiomatic 
https://github.com/darky/glatch
https://github.com/darky/gleaf
