### ISSUE TITLE
return updated value in set

### ISSUE THREAD

**Issue by darky** [Robert4S/gleam_ref#3]
```gleam
pub fn set(cell: RefCell(a), operation: fn(a) -> a) -> a
```

Very often need to deal with updated value after `set` and better to return it

**Comment by Robert4S** [comment]
Done. Just for curiosity, are you using this for something specific, or just checking out new packages?

**Comment by darky** [comment]
I had an idea about `ref` long time ago, but you created it before I began :)
Just share tips, how to improve this library and make it little bit better

**Comment by Robert4S** [comment]
Appreciate it. I'm still quite new to gleam and I do make a lot of mistakes so some code review and suggestions are very useful.
